WProdutive/urls.py
from django.conf.urls import include, url
from django.contrib.auth.views import logout_then_login

from sistema import views as views_sistema
from usuarios import views as views_usuarios

urlpatterns = [
    # Teste angular
    url(r'^angular/$', views_sistema.teste_angular, name='teste_angular'),


    url(r'^$', views_sistema.index, name='index'),
    url(r'^dia/$', views_sistema.dia, name='dia'),
    url(r'^semana/$', views_sistema.semana, name='semana'),
    url(r'^tarefas/', include('tarefas.urls')),
    url(r'^projetos/', include('projetos.urls')),
    url(r'^papeis/', include('papeis.urls')),
    url(r'^lembretes/', include('lembretes.urls')),
    url(r'^usuarios/', include('usuarios.urls')),

    # url(r'^admin/', include(admin.site.urls)),

    # Login autentificacao
    # url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    url(r'^login/$', views_usuarios.fazer_login, name='login'),
    # url(r'^logout/$', logout_then_login, {'login_url': '/login/'}),
    url(r'^sair/$', logout_then_login, {'login_url': '/login/'}, name='logout'),
]

papeis/urls.py
from rest_framework.routers import DefaultRouter

__author__ = 'GuiLe Garcia'
from django.conf.urls import url, include

from . import views

# Create a router and register our viewsets with it. # REST
router = DefaultRouter()
router.register(r'^', views.PapelViewSet)

urlpatterns = [
    url(r'^criar-papel/$', views.criar_papel, name='criar_papel'),
    url(r'^$', views.papeis, name='papeis'),
    url(r'^excluir/(?P<id>\d+)/$', views.excluir_papel, name='excluir_papel'),
    url(r'^editar/$', views.editar_papel, name='editar_papel'),
    url(r'^papel/(?P<id>\d+)/$', views.papel, name='papel'),  # todo mudar para slug

    # REST
    url(r'^api', include(router.urls)),
]

papeis/models.py
from django.contrib.auth.models import User
from django.db import models


class Papel(models.Model):
    nome = models.CharField(max_length=200)
    descricao = models.TextField(blank=True, null=True)
    usuario = models.ForeignKey(User)

    def __init__(self, *args, **kwargs):
        super(Papel, self).__init__(*args, **kwargs)

tarefas/models.py
# coding=utf-8
from django.contrib.auth.models import User
from django.db import models

from papeis.models import Papel
from projetos.models import Projeto


class Tarefa(models.Model):
    titulo = models.CharField(max_length=200)
    descricao = models.TextField(blank=True, null=True)
    data = models.DateField()
    hora = models.TimeField(null=True, blank=True)
    duracao = models.DurationField(blank=True, null=True)
    prioridade = models.IntegerField(default=30, blank=True, null=True)
    status = models.IntegerField(default=0)
    papel = models.ForeignKey(Papel, blank=True, null=True)
    projeto = models.ForeignKey(Projeto, blank=True, null=True)
    usuario = models.ForeignKey(User)
    repetida = models.BooleanField(default=False) # Possui tarefas repetidas?
    tarefa_original = models.ForeignKey('self', blank=True, null=True) # Esta tarefa repete outra?

    def __init__(self, *args, **kwargs):
        super(Tarefa, self).__init__(*args, **kwargs)

templates/includes/botao-adicionar.html
<!-- Botão adicionar -->
<div class="btn-group"> <!--  navbar-right para alinhar-->
  <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
    + Adicionar <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu">
    <li><a href="#" data-toggle="modal" data-target="#criarTarefa">Tarefa</a></li>
    <li><a href="#" data-toggle="modal" data-target="#criarLembrete">Lembrete</a></li>
{#    <li class="divider"></li>#}
  </ul>
</div>
<!-- fim Botão adicionar -->

templates/includes/modal-lembretes.html
<!-- Inicio MODAL Lembrete -->
<div class="modal fade" id="criarLembrete" role="dialog"
     aria-labelledby="Criar e editar lembrete">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" onclick="$('.modal').hide()" class="close" data-dismiss="modal"
                        aria-hidden="true">x
                </button>
                <h4 class="modal-title">Cadastrar Lembrete</h4>
                <em>* itens obrigatórios!</em>
            </div>
            <div class="modal-body">
                <form ng-controller="CriarLembrete as LembreteCtrl" ng-submit="LembreteCtrl.adicionar(lembrete)" id="criar-lembrete" class="form-horizontal"
                      role="form" novalidate> {% csrf_token %}
                    <div class="form-group">
                        <div class="col-sm-2">
                            <label for="id_titulo" class="control-label">Título <abbr title="Campo obrigatório">*</abbr></label>
                        </div>
                        <div class="col-sm-10">
                            <input ng-model="LembreteCtrl.lembrete.titulo" type="text" name="titulo" maxlength="200"
                                   class="form-control" id="id_titulo" placeholder="Título do lembrete">
                        </div>
                    </div>
                    <div class="form-group has-feedback">
                        <div class="col-sm-2">
                            <label for="id_descricao" class="control-label">Descrição</label>
                        </div>
                        <div class="col-sm-10">
                            <textarea ng-model="LembreteCtrl.lembrete.descricao" name="descricao" id="id_descricao" class="form-control" rows="4"
                                      placeholder="Descrição da lembrete.."></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-2">
                            <label class="control-label" for="data_lembrete">Data <abbr title="Campo obrigatório">*</abbr></label>
                        </div>
                        <div class="col-sm-4">
                            <input ng-model="LembreteCtrl.lembrete.data" value="{% now  "Y-m-d" %}" name="data" type="Date" class="form-control" id="data_lembrete" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <input ng-init="LembreteCtrl.lembrete.usuario = {{ user.id }}" ng-model="LembreteCtrl.lembrete.usuario" type="hidden" name="usuario" value="{{ user.id }}">
                            <button type="submit" class="btn btn-success" data-loading-text="Cadastrando...">Cadastrar
                            </button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <a class="btn btn-default" onclick="$('.modal').hide()" data-dismiss="modal">Fechar</a>
            </div>
        </div>
    </div>
</div>
<!-- Fim MODAL Lembrete -->

templates/includes/modal-papeis.html
<!-- Modal Criar Papel  -->
<div class="modal fade" id="criarPapel" tabindex="-1" role="dialog"
     aria-labelledby="Criar e editar Papel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" onclick="$('.modal').hide()" data-dismiss="modal"
                        aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Cadastro de papel</h4>
                <em>* itens obrigatórios!</em>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <form ng-controller="CriarPapel as criarPapel" ng-submit="criarPapel.addPapel(papel)"
                                  method="post" class="form-horizontal" role="form">
                                <!-- <legend draggable="true">Cadastro de papel</legend> -->
                                <div class="form-group col-md-10">
                                    <label for="id_nome">Nome: <abbr title="Campo obrigatório">*</abbr></label>
                                    <input ng-model="criarPapel.papel.nome" name="nome" type="text" class="form-control" value="{{ form.nome.value }}"
                                           maxlength="200" id="id_nome" placeholder="Escreva o nome..">
                                    {% for error in form.nome.errors %}
                                        <p class="text-danger">{{ error|escape }}</p>
                                    {% endfor %}
                                </div>
                                <div class="form-group col-md-12" draggable="true">
                                    <label for="id_descricao">Descricao:</label>
                                    <textarea ng-model="criarPapel.papel.descricao" name="descricao" id="id_descricao" class="form-control" rows="4"
                                              placeholder="Descrição do papel..">{{ form.descricao.value }}</textarea>
                                    {% for error in form.descricao.errors %}
                                        <p class="text-danger">{{ error|escape }}</p>
                                    {% endfor %}

                                </div>
                                <div class="form-group col-md-8">
                                    <input ng-init="criarPapel.papel.usuario = {{ user.id }}" ng-model="criarPapel.papel.usuario" type="hidden" id="id_usuario_papel" name="usuario" >
                                    <button type="submit" class="btn btn-success" draggable="true">Cadastrar</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" onclick="$('.modal').hide()" class="btn btn-default" data-dismiss="modal">Fechar
                </button>
            </div>
        </div>
    </div>
</div>
<!-- fim MODAL papel -->

templates/includes/modal-projetos.html
<!-- MODAL projeto  -->
<div class="modal fade {{ abrir_modal_projeto }}" id="criarProjeto" data-keyboard="true" data-backdrop="true"
     tabindex="-1" role="dialog" aria-labelledby="Criar e editar projeto" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" onclick="$('.modal').hide()" data-dismiss="modal"
                        aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Cadastro de projeto</h4>
                <em>* itens obrigatórios!</em>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="row">
                        <div class="col-md-4">
                            <form ng-controller="CriarProjeto as projetoCreate" ng-submit="projetoCreate.addProjeto(projeto)" class="form-horizontal" role="form" novalidate> {% csrf_token %}
                                <div class="form-group col-md-10">
                                    <label for="id_nome">Nome: <abbr title="Campo obrigatório">*</abbr></label>
                                    <input ng-model="projetoCreate.projeto.nome" name="nome" id="id_nome_projeto" type="text" class="form-control"
                                           value="{{ form.nome.value }}" maxlength="200"
                                           placeholder="Escreva seu nome.." required>
                                    {% for error in form.nome.errors %}
                                        <p class="text-danger">{{ error|escape }}</p>
                                    {% endfor %}

                                </div>
                                <div class="form-group col-md-12" draggable="true">
                                    <label for="id_descricao">Descricao:</label>
                                    <textarea ng-model="projetoCreate.projeto.descricao" name="descricao" id="id_descricao_projeto" class="form-control" rows="4"
                                              placeholder="Descrição da projeto..">{{ form.descricao.value }}</textarea>
                                    {% for error in form.descricao.errors %}
                                        <p class="text-danger">{{ error|escape }}</p>
                                    {% endfor %}

                                </div>

                                <input ng-init="projetoCreate.projeto.usuario = {{ user.id }}" ng-model="projetoCreate.projeto.usuario" type="hidden" id="id_usuario_projeto" name="usuario" >
                                <input type="hidden" id="id_url_projeto" name="url" value="{{ url }}">
                                <input id="id_id_projeto" type="hidden" name="id" value="{{ form.id.value }}">

                                <div class="form-group col-md-8">
                                    <button type="submit" class="btn btn-success" draggable="true"
                                            data-loading-text="Cadastrando...">Cadastrar
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" onclick="$('.modal').hide()" data-dismiss="modal">Fechar
                </button>
            </div>
        </div>
    </div>
</div>
<!-- fim MODAL projeto -->


<!-- MODAL projeto EDITAR  -->
        <div class="modal fade" id="atualizarProjeto" data-keyboard="true" data-backdrop="true"
             tabindex="-1" role="dialog" aria-labelledby="Editar projeto" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" onclick="$('.modal').hide()" data-dismiss="modal"
                                aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Editar projeto</h4>
                        <em>* itens obrigatórios!</em>
                    </div>
                    <div class="modal-body">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-4">
                                    <form ng-submit="ProjetoCtrl.atualizaProjeto(projeto)" class="form-horizontal" role="form" novalidate> {% csrf_token %}
                                        <div class="form-group col-md-10">
                                            <label for="id_nome">Nome: <abbr title="Campo obrigatório">*</abbr></label>
                                            <input ng-model="ProjetoCtrl.projeto.nome" name="nome" id="id_nome_projeto" type="text" class="form-control"
                                                   value="[[ ProjetoCtrl.projeto.nome ]]" maxlength="200" placeholder="Escreva seu nome.." required>
                                            {% for error in form.nome.errors %}
                                                <p class="text-danger">{{ error|escape }}</p>
                                            {% endfor %}

                                        </div>
                                        <div class="form-group col-md-12" draggable="true">
                                            <label for="id_descricao">Descricao:</label>
                                            <textarea ng-model="ProjetoCtrl.projeto.descricao" name="descricao" id="id_descricao_projeto" class="form-control" rows="4"
                                                      placeholder="Descrição da projeto..">[[ projeto.descricao ]]</textarea>
                                            {% for error in form.descricao.errors %}
                                                <p class="text-danger">{{ error|escape }}</p>
                                            {% endfor %}

                                        </div>

                                        <input ng-init="ProjetoCtrl.projeto.usuario = {{ user.id }}" ng-model="ProjetoCtrl.projeto.usuario" type="hidden" id="id_usuario_projeto" name="usuario" >
                                        <input type="hidden" id="id_url_projeto" name="url" value="{{ url }}">
                                        <input id="id_id_projeto" type="hidden" name="id" value="{{ form.id.value }}">

                                        <div class="form-group col-md-8">
                                            <button type="submit" class="btn btn-success" draggable="true" data-loading-text="Cadastrando...">Atualizar</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" onclick="$('.modal').hide()" data-dismiss="modal">Fechar
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <!-- fim MODAL projeto -->

templates/includes/modal-tarefas.html
<!-- Modal Tarefa -->
<div class="modal fade" id="atualizarTarefa" role="dialog" aria-labelledby="Editar tarefa">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" onclick="$('.modal').hide()" class="close" data-dismiss="modal"
                        aria-hidden="true">x
                </button>
                <h4 class="modal-title">Editar Tarefa</h4>
                <em>* itens obrigatórios!</em>
            </div>
            <div class="modal-body">
                <form ng-submit="TarefaCtrl.update(tarefa)" class="form-horizontal" method="post" role="form" novalidate>{% csrf_token %}
                    <div class="form-group">
                        <div class="col-sm-2">
                            <label for="id_titulo_tarefa" class="control-label">Título <abbr
                                    title="Campo obrigatório">*</abbr></label>
                        </div>
                        <div class="col-sm-10">
                            <input ng-model="TarefaCtrl.tarefa.titulo" name="titulo" type="text" class="form-control" maxlength="200" id="id_titulo_tarefa" placeholder="Escreva o título da tarefa.." required>
                        </div>
                    </div>
                    <div class="form-group has-feedback">
                        <div class="col-sm-2">
                            <label for="id_descricao_tarefa" class="control-label">Descrição</label>
                        </div>
                        <div class="col-sm-10">
                            <textarea ng-model="TarefaCtrl.tarefa.descricao" name="descricao" id="id_descricao_tarefa" class="form-control" rows="4"
                                      placeholder="Descrição da tarefa.."></textarea>
                        </div>
                    </div>
                    <!-- Data e hora -->
                    <!-- Data -->
                    <div class="form-group">
                        <div class="form-inline">
                            <div class="col-sm-2">
                                <label for="id_data_tarefa" class="control-label">Data <abbr
                                        title="Campo obrigatório">*</abbr></label>
                            </div>
                            <div class="col-sm-4">
                                <!-- todo setar valor default com o now-->
                                <input ng-model="TarefaCtrl.tarefa.data" id="id_data_tarefa" name="data" type="Date" value="{% now  "Y-m-d" %}"
                                       class="form-control" required>
                            </div>
                        </div>
                        <!-- fim Data -->
                        <!-- Hora -->
                        <div class="form-inline">
                            <div class="col-sm-2">
                                <label for="id_hora_tarefa" class="control-label">Hora</label>
                            </div>
                            <div class="col-sm-4">
                                <!-- todo como vou formatar a hora? Ideia: ng-init -->
                                <input ng-model="TarefaCtrl.tarefa.hora" name="hora" type="Time" value="{{ form.hora.value|time:"H:i" }}"
                                      placeholder="xx:xx" class="form-control" id="id_hora_tarefa">
                            </div>
                        </div>
                        <!-- fim Hora -->
                    </div>
                    <!-- fim Data e Hora-->
                    <hr/>
                    <!-- Duraçaõ e Prioridade -->
                    <div class="form-group">
                        <!-- Duração -->
                        <div class="form-inline">
                            <div class="col-sm-2">
                                <label for="id_duracao_tarefa" class="control-label">Duração</label>
                            </div>
                            <div class="col-sm-4">
                                <input ng-model="TarefaCtrl.tarefa.duracao" name="duracao" type="Time" value="{{ form.duracao.value|time:"H:i" }}"
                                           class="form-control" id="id_duracao_tarefa">
                            </div>
                        </div>
                        <!-- fim Duração -->
                        <!-- Prioridade -->
                        <div class="form-inline">
                            <div class="col-sm-2">
                                <label for="id_prioridade_tarefa" class="control-label">Prioridade</label>
                            </div>
                            <div class="col-sm-4">
                                <select ng-model="TarefaCtrl.tarefa.prioridade" name="prioridade" class="form-control" id="id_prioridade_tarefa">
                                    <!-- todo como vou mostrar o selecionado ou exibir o "Selecione"? -->
{#                                    {% if form.prioridade.value %}#}
{#                                        <option value="{{ form.prioridade.value }}"#}
{#                                                selected="">{{ form.prioridade.value }}</option>#}
{#                                    {% else %}#}
{#                                        <option value="" selected="" disabled="">Selecione</option>#}
{#                                    {% endif %}#}
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                    <option value="5">5</option>
                                    <option value="6">6</option>
                                    <option value="7">7</option>
                                    <option value="8">8</option>
                                    <option value="9">9</option>
                                    <option value="10">10</option>
                                </select>
                            </div>
                        </div>
                        <!-- fim Prioridade -->
                    </div>
                    <!-- Duração e Prioridade -->
                    <hr>
                    <!-- Projeto e Papel (inline) -->
                    <div class="form-group">
                        <div class="form-inline">
                            <div class="col-sm-2">
                                <label for="id_papel_tarefa" class="control-label">Papel</label>
                            </div>
                            <div class="col-sm-4">
                                <!-- todo remover o style inline -->
                                <select ng-model="TarefaCtrl.tarefa.papel" name="papel" class="form-control" style="width: 150px;" id="id_papel_tarefa">
                                    <option value="" selected="" disabled="">Selecione</option>
                                    <!-- todo usar ng-repeat para papeis -->
                                    {% for papel in request.session.papeis %}
                                        <option value="{{ papel.id }}">{{ papel.nome }}</option>
                                    {% empty %}
                                        <option value="" selected="" disabled="">Nenhum</option>
                                    {% endfor papeis %}
                                </select>
                            </div>
                        </div>
                        <!-- Projeto -->
                        <div class="form-inline">
                            <div class="col-sm-2">
                                <label for="id_projeto_tarefa" class="control-label"
                                       contenteditable="true">Projeto</label>
                            </div>
                            <div class="col-sm-4">
                                <!-- todo remover o style inline -->
                                <select ng-model="TarefaCtrl.tarefa.projeto" name="projeto" class="form-control" style="width: 150px;"
                                        id="id_projeto_tarefa">
                                    <!-- todo usar ng-repeat para papeis --
                                    <!-- todo verificar se a tarefa possui projeto e imprimir nome e id como opção selecionada -->
                                    <option value="" selected="" disabled="">Selecione</option>
                                    {% for projeto in request.session.projetos %}
                                        <option value="{{ projeto.id }}">{{ projeto.nome }}</option>
                                    {% empty %}
                                        <option value="" selected="" disabled="">Nenhum</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <!-- fim Projeto -->
                    </div>
                    <!-- Projeto e Papel (inline) -->
                    <hr/>
                    <!-- Repetir -->
                    <div class="form-group">
                        <div class="form-inline">
                            <div class="col-sm-2">
                                <label for="id_repeticao_tarefa" class="control-label">Repetir</label>
                            </div>
                            <div class="col-sm-3">
                                <select ng-model="TarefaCtrl.tarefa.repeticao" name="repeticao" class="form-control" id="id_repeticao_tarefa">
                                    <option value="" selected="" disabled="">Selecione</option>
                                    <option value="diario">Diariamente</option>
                                    <option value="semanal">Semanal</option>
                                    <option value="mensal">Mensal</option>
                                    <option value="anual">Anual</option>
                                </select>
                            </div>
                        </div>
                        <!-- Nùmero repetições -->
                        <div class="form-inline">
                            <div class="col-sm-2">
                                <input ng-model="TarefaCtrl.tarefa.num_repeticao" name="num_repeticao" type="number" placeholder="Número de repetições!"
                                       class="form-control">
                            </div>
                        </div>
                    </div>
                    <!-- fim repetir -->
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <input ng-init="TarefaCtrl.tarefa.usuario = {{ user.id }}" ng-model="TarefaCtrl.tarefa.usuario" type="hidden" name="usuario" value="{{ user.id }}">
                           <input type="hidden" name="id" value="[[ TarefaCtrl.tarefa.pk ]]" id="tarefa_id_id">
                            <button id="button_editar_tarefa" type="submit" class="btn btn-success pull-left">Atualizar</button>

                        </div>
                    </div>
                </form>
            </div>
            <!--
            <div class="modal-footer">
                <a class="btn btn-default" class="close" onclick="$('.modal').hide()" data-dismiss="modal">Fechar</a>
            </div>
            -->
        </div>
    </div>
</div>
<!-- fim Modal Tarefa -->